import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/server/supabase-admin";
import { lookupPatientByMobile, hashOtp } from "@/lib/server/patient-auth";

/**
 * POST /api/patient-auth/verify-otp
 * 
 * Verifies the 6-digit OTP entered by the patient.
 * Checks expiry, attempt count limits, and compares the hashed OTP.
 * On success, generates a short-lived verification token stored in `otp_verified_sessions`.
 * 
 * Body: { mobile_number: string, otp_code: string }
 */
export async function POST(request: Request): Promise<NextResponse> {
  let body: { mobile_number?: string; otp_code?: string };
  try {
    body = await request.json() as { mobile_number?: string; otp_code?: string };
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { mobile_number, otp_code } = body;
  if (!mobile_number || !otp_code) {
    return NextResponse.json(
      { error: "mobile_number and otp_code are required" },
      { status: 400 }
    );
  }

  // 1. Call lookup utility to get patient_id
  const patient = await lookupPatientByMobile(mobile_number);
  if (!patient) {
    return NextResponse.json(
      { message: "No patient found with this number" },
      { status: 404 }
    );
  }

  const { patient_id } = patient;
  const admin = createAdminClient();

  // 2. Fetch active OTP session for that patient_id from otp_sessions
  const { data: session, error: fetchError } = await admin
    .from("otp_sessions")
    .select("*")
    .eq("patient_id", patient_id)
    .maybeSingle();

  if (fetchError || !session) {
    return NextResponse.json(
      { message: "No active verification session found. Please request a new OTP." },
      { status: 400 }
    );
  }

  const now = new Date();
  const expiresAt = new Date(session.expires_at);

  // 3. Check: OTP not expired
  if (now > expiresAt) {
    // Delete expired session to keep DB clean
    await admin.from("otp_sessions").delete().eq("patient_id", patient_id);
    return NextResponse.json(
      { message: "Your verification code has expired. Please request a new OTP." },
      { status: 400 }
    );
  }

  // 4. Check: attempts < 5
  if (session.attempts >= 5) {
    await admin.from("otp_sessions").delete().eq("patient_id", patient_id);
    return NextResponse.json(
      { message: "Too many failed attempts. Please request a new OTP." },
      { status: 400 }
    );
  }

  // Hash the incoming raw OTP and compare
  const hashedInput = hashOtp(otp_code.trim());
  const match = hashedInput === session.otp_hash;

  if (!match) {
    const nextAttempts = session.attempts + 1;
    if (nextAttempts >= 5) {
      // Invalidate on 5th failure
      await admin.from("otp_sessions").delete().eq("patient_id", patient_id);
      return NextResponse.json(
        { message: "Too many failed attempts. Please request a new OTP." },
        { status: 401 }
      );
    } else {
      // Increment attempts
      await admin
        .from("otp_sessions")
        .update({ attempts: nextAttempts })
        .eq("patient_id", patient_id);
      
      const remaining = 5 - nextAttempts;
      return NextResponse.json(
        { message: `Incorrect verification code. You have ${remaining} attempts remaining.` },
        { status: 401 }
      );
    }
  }

  // 5. Success! Generate a short-lived otp_token (expired in 15 minutes)
  const tokenExpiresAt = new Date(Date.now() + 15 * 60 * 1000).toISOString();
  
  const { data: verifiedSession, error: tokenError } = await admin
    .from("otp_verified_sessions")
    .insert({
      patient_id,
      expires_at: tokenExpiresAt,
      used: false,
    })
    .select("token")
    .single();

  if (tokenError || !verifiedSession) {
    console.error("Failed to generate verified token session:", tokenError);
    return NextResponse.json(
      { error: "Internal server error during verification" },
      { status: 500 }
    );
  }

  // Delete the successfully verified OTP session
  await admin.from("otp_sessions").delete().eq("patient_id", patient_id);

  // Return the token (UUID generated by db default gen_random_uuid())
  return NextResponse.json({
    otp_token: verifiedSession.token,
  });
}
